"""Third

Revision ID: 3ce3b009847b
Revises: b613bc27d956
Create Date: 2022-03-23 16:20:12.680978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce3b009847b'
down_revision = 'b613bc27d956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
