"""Four

Revision ID: d33b9794d651
Revises: 3ce3b009847b
Create Date: 2022-03-23 16:25:45.532032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33b9794d651'
down_revision = '3ce3b009847b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_id_key', 'booking', type_='unique')
    op.drop_constraint('queue_id_key', 'queue', type_='unique')
    op.drop_constraint('tables_id_key', 'tables', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tables_id_key', 'tables', ['id'])
    op.create_unique_constraint('queue_id_key', 'queue', ['id'])
    op.create_unique_constraint('booking_id_key', 'booking', ['id'])
    # ### end Alembic commands ###
